Algoritmo "EX_EA_14"
// Disciplina   : [Lógica de Programação]
// Professor   : Esdras Bezerra da Silva 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/7/2023
Var
// Seção de Declarações das variáveis 

   x,r:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  leia(x)
   r <- x * 0.3
  escreval("30% de ", x, " é ", r)
Fimalgoritmo